#!/usr/bin/env python3

import argparse
import socket
import time
import json
import select
import struct
import math
import copy

# DEBUG = True
DEBUG = False

parser = argparse.ArgumentParser(description='route packets')
parser.add_argument('asn', type=int, help="AS Number")
parser.add_argument('networks', metavar='networks',
                    type=str, nargs='+', help="networks")
args = parser.parse_args()

##########################################################################################

# Message Fields
TYPE = "type"
SRCE = "src"
DEST = "dst"
MESG = "msg"
TABL = "table"

# Message Types
DATA = "data"
DUMP = "dump"
UPDT = "update"
RVKE = "revoke"
NRTE = "no route"

# Update Message Fields
NTWK = "network"
NMSK = "netmask"
ORIG = "origin"
LPRF = "localpref"
APTH = "ASPath"
SORG = "selfOrigin"

# internal route info
CUST = "cust"
PEER = "peer"
PROV = "prov"


##########################################################################################

class Router:

    routes = None
    coalesced_routes = None
    updates = None
    relations = None
    sockets = None

    def __init__(self, networks):
        self.routes = []
        self.coalesced_routes = []
        self.updates = []
        self.relations = {}
        self.sockets = {}
        for relationship in networks:
            network, relation = relationship.split("-")
            if DEBUG:
                print("Starting socket for", network, relation)
            self.sockets[network] = socket.socket(
                socket.AF_UNIX, socket.SOCK_SEQPACKET)
            self.sockets[network].setblocking(0)
            self.sockets[network].connect(network)
            self.relations[network] = relation
        return

    def ip_to_bin(self, ip):
        """ Convert String ip address to binary int """
        parts = ip.split(".")
        int_parts = list(map(int, parts))
        binary = '{0:08b}{1:08b}{2:08b}{3:08b}'.format(*int_parts)
        return int(binary, 2)

    def get_mask_length(self, mask):
        """ Determine the length of the netmask string """
        parts = mask.split(".")
        int_parts = list(map(int, parts))
        binary = '{0:08b}{1:08b}{2:08b}{3:08b}'.format(*int_parts)
        try:
            return binary.index("0")
        except ValueError:
            return len(binary)

    def lookup_routes(self, daddr):
        """ Lookup all valid routes for an address """
        """ Only returns matches that have the longest matching netmask """
        outroutes = []
        longest_mask_length = None
        for r in self.coalesced_routes:
            if (self.ip_to_bin(daddr) ^ self.ip_to_bin(r[NTWK])) & self.ip_to_bin(r[NMSK]) == 0:
                cur_mask_length = self.get_mask_length(r[NMSK])
                if longest_mask_length is None or cur_mask_length > longest_mask_length:
                    longest_mask_length = cur_mask_length
                    outroutes = [r]
                elif cur_mask_length == longest_mask_length:
                    outroutes.append(r)
        return outroutes

    def get_shortest_as_path(self, routes):
        """ select the route with the shortest AS Path """
        outroutes = []
        shortest = -1
        for route in routes:
            cur = len(route[APTH])
            if shortest == -1 or cur == shortest:
                shortest = cur
                outroutes.append(route)
            elif cur < shortest:
                shortest = cur
                outroutes = []
                outroutes.append(route)
        if DEBUG:
            print("Minimized potential routes to shortest paths:")
            print(outroutes)
        return outroutes

    def get_highest_preference(self, routes):
        """ select the route with the highest preference """
        outroutes = []
        highest = -1
        for route in routes:
            cur = route[LPRF]
            if highest == -1 or cur == highest:
                highest = cur
                outroutes.append(route)
            elif cur > highest:
                highest = cur
                outroutes = []
                outroutes.append(route)
        if DEBUG:
            print("Minimized potential routes to highest preference:")
            print(outroutes)
        return outroutes

    def get_self_origin(self, routes):
        """ select self originating routes """
        outroutes = []
        for route in routes:
            if route[SORG]:
                outroutes.append(route)
        if not outroutes:
            outroutes = routes
        if DEBUG:
            print("Minimized potential routes to self originating (if any):")
            print(outroutes)
        return outroutes

    def get_origin_routes(self, routes):
        """ select origin routes: EGP > IGP > UNK """
        egp_routes = []
        igp_routes = []
        unk_routes = []

        for route in routes:
            if route[ORIG] == "EGP":
                egp_routes.append(route)
            elif route[ORIG] == "IGP":
                igp_routes.append(route)
            elif route[ORIG] == "UNK":
                unk_routes.append(route)

        outroutes = []
        if len(igp_routes) != 0:
            outroutes = igp_routes
        elif len(egp_routes) != 0:
            outroutes = egp_routes
        else:
            outroutes = unk_routes

        if DEBUG:
            print("Minimized potential routes by origin:")
            print(outroutes)

        return outroutes

    def filter_relationships(self, srcif, routes):
        """ Don't allow Peer->Peer, Peer->Prov, or Prov->Peer forwards """
        outroutes = []
        if DEBUG:
            print('Relations: ' + self.relations)
        for r in routes:
            if self.relations[srcif] == CUST or self.relations[r[PEER]] == CUST:
                outroutes.append(r)
        return outroutes

    def lowest_ip_address_routes(self, routes):
        """ Selec the route with the lowest IP address """
        outroutes = []
        lowest = ""
        for route in routes:
            l = lowest.split('.')[0]
            p = route[PEER].split('.')[0]
            if not lowest or l > p:
                lowest = route[PEER]
                outroutes = []
                outroutes.append(route)
            elif l == p:
                outroutes.append(route)
        if DEBUG:
            print("Minimized potential routes by lowest ip:")
            print(outroutes)
        return outroutes

    def get_route(self, srcif, daddr):
        """	Select the best route for a given address	"""
        peer = None
        routes = self.lookup_routes(daddr)
        if routes:
            # 1. Highest Preference
            routes = self.get_highest_preference(routes)
            # 2. Self Origin
            routes = self.get_self_origin(routes)
            # 3. Shortest ASPath
            routes = self.get_shortest_as_path(routes)
            # 4. EGP > IGP > UNK
            routes = self.get_origin_routes(routes)
            # 5. Lowest IP Address
            routes = self.lowest_ip_address_routes(routes)
            # Final check: enforce peering relationships
            routes = self.filter_relationships(srcif, routes)
        if len(routes) >= 1:
            peer = routes[0][PEER]
        return self.sockets[peer] if peer else None

    def forward(self, srcif, packet):
        """	Forward a data packet	"""
        dest = copy.copy(packet)[DEST]
        routes = self.lookup_routes(dest)

        if len(routes) == 0:
            # router does not have a route to the given destination, send back
            self.no_route_send_back(packet)
        elif len(routes) == 1:
            # forward the data packet on the appropriate port
            sock = routes[0][PEER]
            if self.relations[srcif] == CUST or self.relations[sock] == CUST:
                serialized = json.dumps(packet)
                self.sockets[sock].sendall(serialized.encode(
                    encoding='ascii', errors='strict'))
            else:
                self.no_route_send_back(packet)
        else:
            # multiple routes, use routing logic
            sock = self.get_route(srcif, dest)
            if not sock:
                self.no_route_send_back(packet)

            serialized = json.dumps(packet)
            sock.sendall(serialized.encode(
                encoding='ascii', errors='strict'))

    def no_route_send_back(self, packet):
        """	Send No Route message back to sender when no route found """
        to_send = {
            "dst": packet[SRCE],
            "type": "no route",
            "msg": {},
        }
        sock = self.lookup_routes(packet[SRCE])[0][PEER]
        to_send[SRCE] = sock[:-1] + "1"

        serialized = json.dumps(to_send)
        self.sockets[sock].sendall(serialized.encode(
            encoding='ascii', errors='strict'))

    def equal_route_fields(self, route_a, route_b):
        """ determine if two routes are equal and candidates for aggregation """
        return route_a[PEER] == route_b[PEER] and route_a[LPRF] == route_b[LPRF] and route_a[NMSK] == route_b[NMSK] and route_a[APTH] == route_b[APTH] and route_a[ORIG] == route_b[ORIG] and route_a[SORG] == route_b[SORG]

    def is_neighbors(self, route_a, route_b):
        """ determine if two routes are neighbors and candidates for aggregation """
        mask_length_a = self.get_mask_length(route_a[NMSK])
        mask_length_b = self.get_mask_length(route_b[NMSK])
        # Expect network dif to be a single "1" at mask_length - 1
        net_dif = self.ip_to_bin(
            route_a[NTWK]) ^ self.ip_to_bin(route_b[NTWK])
        net_string = '{0:32b}'.format(net_dif)
        return mask_length_a == mask_length_b and net_string.index("1") == mask_length_a - 1 and net_string.rfind("1") == mask_length_a - 1

    def shorten_mask(self, mask):
        """ take the string netmask and return the string netmask shortened by 1 in length """
        new_mask = []
        parts = mask.split(".")
        altered = False
        for part in reversed(parts):
            if part != "0" and not altered:
                binary = '{0:08b}'.format(int(part))
                last_one_index = binary.rfind("1")
                new_binary = binary[:last_one_index] + \
                    "0" + binary[last_one_index + 1:]
                new_part = str(int(new_binary, 2))
                new_mask.insert(0, new_part)
                altered = True
            else:
                new_mask.insert(0, part)

        return ".".join(new_mask)

    def join_routes(self, route_a, route_b):
        """ aggregate two routes into a single route """
        ret = {
            LPRF: route_a[LPRF],
            APTH: route_a[LPRF],
            ORIG: route_a[ORIG],
            SORG: route_a[SORG],
            PEER: route_a[PEER]
        }
        # take the lesser of the networks
        net_a = self.ip_to_bin(route_a[NTWK])
        net_b = self.ip_to_bin(route_b[NTWK])
        ret[NTWK] = route_a[NTWK] if net_a < net_b else route_b[NTWK]
        # take the netmask with length - 1
        ret[NMSK] = self.shorten_mask(route_a[NMSK])
        return ret

    def coalesce_helper(self, routes):
        """ recursive coalesce function """
        coalesced_routes = []
        for i in range(len(routes) - 1):
            for j in range(i + 1, len(routes)):
                if self.equal_route_fields(routes[i], routes[j]) and self.is_neighbors(routes[i], routes[j]):
                    coalesced_routes.append(
                        self.join_routes(routes[i], routes[j]))
                    if j < len(routes):
                        coalesced_routes.extend(routes[j + 1:len(routes)])
                    return self.coalesce_helper(coalesced_routes)
            coalesced_routes.append(routes[i])
        return routes

    def coalesce(self):
        """	coalesce any routes that are right next to each other	"""
        self.coalesced_routes = self.coalesce_helper(self.routes)
        return True

    def pervade_update(self, srcif, packet):
        """ handle spreading update """
        other_neighbors = list(filter(lambda x: x != srcif, self.sockets))
        to_send = copy.deepcopy(packet)
        if packet[TYPE] == UPDT:
            to_send[MESG][APTH].append(args.asn)
        for sock in other_neighbors:
            to_send[SRCE] = sock[:-1] + "1"
            to_send[DEST] = sock
            if self.relations[sock] == CUST or self.relations[srcif] == CUST:
                if DEBUG:
                    print("Sending update:\n", to_send)
                serialized = json.dumps(to_send)
                self.sockets[sock].sendall(serialized.encode(
                    encoding='ascii', errors='strict'))

    def update(self, srcif, packet):
        """	handle update packets	"""
        # (1) Save a copy of the announcement
        self.updates.append(packet)
        # (2) Add an entry to the forwarding table
        msg = copy.deepcopy(packet)[MESG]
        msg.update({"peer": packet[SRCE]})
        self.routes.append(msg)
        self.coalesce()
        # (3) Forward update message to neighbors
        self.pervade_update(srcif, packet)
        return True

    def revoke(self, srcif, packet):
        """ handle revoke packets   """
        # Save copy of revoke announcement for later
        self.updates.append(packet)
        # Remove dead entries from revoke in routing table
        newRoutes = []
        for r in packet[MESG]:
            for route in self.routes:
                if (route["network"] != r["network"] or route["netmask"] != r["netmask"] or route["peer"] != packet[SRCE]):
                    newRoutes.append(route)

        self.routes = copy.deepcopy(newRoutes)
        self.coalesce() # disaggregation
        self.pervade_update(srcif, packet)
        return True

    def dump(self, packet):
        """	handles dump table requests	"""
        msg = []
        for route in self.coalesced_routes:
            msg.append({
                "network": route["network"],
                "netmask": route["netmask"],
                "peer": route[PEER]
            })
        to_send = {
            "src": packet[DEST],
            "dst": packet[SRCE],
            "type": "table",
            "msg": msg,
        }
        if DEBUG:
            print("Sending dump:\n", to_send)
        serialized = json.dumps(to_send)
        self.sockets[packet[SRCE]].sendall(serialized.encode(
            encoding='ascii', errors='strict'))
        return True

    def handle_packet(self, srcif, packet):
        """	dispatches a packet """
        packet_type = packet[TYPE]
        if (packet_type == UPDT):
            return self.update(srcif, packet)
        elif (packet_type == DATA):
            return self.forward(srcif, packet)
        elif (packet_type == DUMP):
            return self.dump(packet)
        elif (packet_type == RVKE):
            return self.revoke(srcif, packet)
        else:
            raise ValueError("Invalid packet type")

    def send_error(self, conn, msg):
        """ Send a no_route error message """
        return

    def run(self):
        while True:
            socks = select.select(self.sockets.values(), [], [], 0.1)[0]
            for conn in socks:
                try:
                    k = conn.recv(65535)
                except:
                    # either died on a connection reset, or was SIGTERM's by parent
                    return
                if k:
                    for sock in self.sockets:
                        if self.sockets[sock] == conn:
                            srcif = sock
                    msg = json.loads(k)
                    if DEBUG:
                        print("Received message:\n", msg)
                    if not self.handle_packet(srcif, msg):
                        self.send_error(conn, msg)
                else:
                    return
        return


if __name__ == "__main__":
    router = Router(args.networks)
    router.run()
